# Writeable directory for the file lock (prevents concurrent runs)
flockdir: "/var/lib/sequencer/flock"

# Name of the lock file inside flockdir
lock_file_name: "sequencer-sync.lock"

# Writeable directory for log files (transfer log, run log, cron file)
logdir: "/var/lib/sequencer/log"

# Search for subdirectories under the source for new sequencing runs.
# Each run is assumed to be one directory.
source: "/data/nanopore"

# We might want to distinguish e.g. core facility run (copy only fastq)
# versus project runs (copy also raw data).
# These are distinct categories. Each sequencing run (directory) is
# classified as a category based on whether its directory name matches
# the regex. Categories are checked top from bottom; first match classifies.

category:
  - # If directory matches this regex, the run is classified
    # as this category.
    # Regexes are searched top to bottom; first one classifies the run
    regex: "^ONT_WGS_"

   # Destination: To same machine - move to this particular directory
    destination:
      type: local
      path: "/var/lib/sequencer/landing-zone-core"

    # Passed to rsync command with --exclude
    exclude:
      - "*_skip"
      - "pod5*"

    # Only if every glob in this list matches at least one file in the
    # directory, we consider the sequencing run complete. Incomplete runs
    # are skipped by default.
    completion_file_globs:
      - "*/*/report*.html"

    # If this is set to true (default false), then a directory name "240101_NB123"
    # is transferred into "<destination.path>/2024/240101_NB123".
    # The "2024/" is "20" + the first two characters of the directory name,
    # If this is set, then the directory name MUST begin with two digits.
    # Ensure regex is set to only capture dir names with two leading digits.
    year_subdirectory: false

  - regex: "^ONT_"

    # Destination type: Remote server you have passwordless SSH access to
    # SSHs to sequencer-sync@sequencer.example.org:/srv/sequencer/landing-zone-other
    destination:
      type: remote
      user: "sequencer-sync"
      host: "sequencer.example.org"
      port: 22
      path: "/srv/sequencer/landing-zone-other"
    exclude:
      - "*_skip"
      - "pod5*"
    completion_file_globs:
      - "*/*/report*.html"
