flockdir = "/var/lib/sequencer/flock"
server_user = "sequencer-sync"
server_port = 22
server_host = "sequencer.example.org"
source = "/data/nanopore"

[[category]]
regex = "^ONT_WGS_"
landing_zone = "/var/lib/sequencer/landing-zone-core"
exclude = ["*_skip", "pod5*"]
completion_file_glob = "report*.html"

[[category]]
regex = "^ONT_"
landing_zone = "/var/lib/sequencer/landing-zone-other"
exclude = ["*_skip", "pod5*"]
completion_file_glob = "report*.html"
